<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://www.example.com/Origination/bpel/OriginationAsynchronousPostBackProcessArtifacts" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:wsdl="http://Radian.Matrix.MortgageIns.Origination.RateQuote" name="OriginationAsynchronousPostBackProcessArtifacts" targetNamespace="http://www.example.com/Origination/bpel/OriginationAsynchronousPostBackProcessArtifacts">
</definitions>
